# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1075, 593)
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(69, 74, 73, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(104, 111, 110, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        brush3 = QBrush(QColor(86, 92, 91, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        brush4 = QBrush(QColor(35, 37, 37, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush4)
        brush5 = QBrush(QColor(46, 49, 49, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush6 = QBrush(QColor(0, 0, 0, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush6)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        brush7 = QBrush(QColor(34, 37, 36, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush7)
        brush8 = QBrush(QColor(255, 255, 220, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
        brush9 = QBrush(QColor(255, 255, 255, 128))
        brush9.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush9)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush9)
#endif
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush9)
#endif
        MainWindow.setPalette(palette)
        MainWindow.setStyleSheet(u"")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.lineEdit_nombre_netlist = QLineEdit(self.centralwidget)
        self.lineEdit_nombre_netlist.setObjectName(u"lineEdit_nombre_netlist")
        self.lineEdit_nombre_netlist.setGeometry(QRect(20, 230, 211, 21))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush6)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush6)
        brush10 = QBrush(QColor(0, 0, 0, 128))
        brush10.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush10)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        brush11 = QBrush(QColor(0, 0, 0, 128))
        brush11.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush11)
#endif
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        brush12 = QBrush(QColor(0, 0, 0, 128))
        brush12.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush12)
#endif
        self.lineEdit_nombre_netlist.setPalette(palette1)
        self.pushButton_abrir_netlist = QPushButton(self.centralwidget)
        self.pushButton_abrir_netlist.setObjectName(u"pushButton_abrir_netlist")
        self.pushButton_abrir_netlist.setGeometry(QRect(230, 230, 81, 23))
        self.pushButton_abrir_netlist.setStyleSheet(u"background-color:qlineargradient(spread:pad, x1:0.568, y1:0.0454545, x2:0.511, y2:0.994318, stop:0 rgba(88, 191, 162, 255), stop:1 rgba(90, 170, 126, 255));")
        self.pushButton_abrir_touchstone = QPushButton(self.centralwidget)
        self.pushButton_abrir_touchstone.setObjectName(u"pushButton_abrir_touchstone")
        self.pushButton_abrir_touchstone.setGeometry(QRect(980, 320, 81, 23))
        self.pushButton_abrir_touchstone.setStyleSheet(u"background-color:qlineargradient(spread:pad, x1:0.568, y1:0.0454545, x2:0.511, y2:0.994318, stop:0 rgba(88, 191, 162, 255), stop:1 rgba(90, 170, 126, 255));")
        self.lineEdit_nombre_touchstone = QLineEdit(self.centralwidget)
        self.lineEdit_nombre_touchstone.setObjectName(u"lineEdit_nombre_touchstone")
        self.lineEdit_nombre_touchstone.setGeometry(QRect(770, 320, 211, 21))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush6)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush6)
        brush13 = QBrush(QColor(0, 0, 0, 128))
        brush13.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Active, QPalette.PlaceholderText, brush13)
#endif
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        brush14 = QBrush(QColor(0, 0, 0, 128))
        brush14.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush14)
#endif
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        brush15 = QBrush(QColor(0, 0, 0, 128))
        brush15.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush15)
#endif
        self.lineEdit_nombre_touchstone.setPalette(palette2)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(770, 300, 141, 16))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 210, 131, 16))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(400, 170, 61, 16))
        self.comboBox_grafica_2 = QComboBox(self.centralwidget)
        self.comboBox_grafica_2.addItem("")
        self.comboBox_grafica_2.addItem("")
        self.comboBox_grafica_2.addItem("")
        self.comboBox_grafica_2.setObjectName(u"comboBox_grafica_2")
        self.comboBox_grafica_2.setGeometry(QRect(770, 510, 211, 21))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush6)
        palette3.setBrush(QPalette.Active, QPalette.Button, brush)
        palette3.setBrush(QPalette.Active, QPalette.Light, brush)
        palette3.setBrush(QPalette.Active, QPalette.Midlight, brush)
        brush16 = QBrush(QColor(127, 127, 127, 255))
        brush16.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.Dark, brush16)
        brush17 = QBrush(QColor(170, 170, 170, 255))
        brush17.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.Mid, brush17)
        palette3.setBrush(QPalette.Active, QPalette.Text, brush6)
        palette3.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette3.setBrush(QPalette.Active, QPalette.ButtonText, brush6)
        palette3.setBrush(QPalette.Active, QPalette.Base, brush)
        palette3.setBrush(QPalette.Active, QPalette.Window, brush)
        palette3.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette3.setBrush(QPalette.Active, QPalette.AlternateBase, brush)
        palette3.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette3.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
        brush18 = QBrush(QColor(0, 0, 0, 128))
        brush18.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Active, QPalette.PlaceholderText, brush18)
#endif
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Midlight, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Dark, brush16)
        palette3.setBrush(QPalette.Inactive, QPalette.Mid, brush17)
        palette3.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        palette3.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.ButtonText, brush6)
        palette3.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Window, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette3.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette3.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush6)
        brush19 = QBrush(QColor(0, 0, 0, 128))
        brush19.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush19)
#endif
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush16)
        palette3.setBrush(QPalette.Disabled, QPalette.Button, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.Midlight, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.Dark, brush16)
        palette3.setBrush(QPalette.Disabled, QPalette.Mid, brush17)
        palette3.setBrush(QPalette.Disabled, QPalette.Text, brush16)
        palette3.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.ButtonText, brush16)
        palette3.setBrush(QPalette.Disabled, QPalette.Base, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.Window, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.Shadow, brush6)
        palette3.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette3.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush6)
        brush20 = QBrush(QColor(0, 0, 0, 128))
        brush20.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush20)
#endif
        self.comboBox_grafica_2.setPalette(palette3)
        self.pushButton_graficar_2 = QPushButton(self.centralwidget)
        self.pushButton_graficar_2.setObjectName(u"pushButton_graficar_2")
        self.pushButton_graficar_2.setGeometry(QRect(980, 510, 81, 23))
        self.pushButton_graficar_2.setStyleSheet(u"background-color:qlineargradient(spread:pad, x1:0.568, y1:0.0454545, x2:0.511, y2:0.994318, stop:0 rgba(88, 191, 162, 255), stop:1 rgba(90, 170, 126, 255));")
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(770, 490, 161, 16))
        self.comboBox_parametros = QComboBox(self.centralwidget)
        self.comboBox_parametros.addItem("")
        self.comboBox_parametros.addItem("")
        self.comboBox_parametros.addItem("")
        self.comboBox_parametros.addItem("")
        self.comboBox_parametros.addItem("")
        self.comboBox_parametros.setObjectName(u"comboBox_parametros")
        self.comboBox_parametros.setGeometry(QRect(470, 170, 51, 21))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush6)
        palette4.setBrush(QPalette.Active, QPalette.Button, brush)
        palette4.setBrush(QPalette.Active, QPalette.Light, brush)
        palette4.setBrush(QPalette.Active, QPalette.Midlight, brush)
        palette4.setBrush(QPalette.Active, QPalette.Dark, brush16)
        palette4.setBrush(QPalette.Active, QPalette.Mid, brush17)
        palette4.setBrush(QPalette.Active, QPalette.Text, brush6)
        palette4.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette4.setBrush(QPalette.Active, QPalette.ButtonText, brush6)
        palette4.setBrush(QPalette.Active, QPalette.Base, brush)
        palette4.setBrush(QPalette.Active, QPalette.Window, brush)
        palette4.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette4.setBrush(QPalette.Active, QPalette.AlternateBase, brush)
        palette4.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette4.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
        brush21 = QBrush(QColor(0, 0, 0, 128))
        brush21.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Active, QPalette.PlaceholderText, brush21)
#endif
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        palette4.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Midlight, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Dark, brush16)
        palette4.setBrush(QPalette.Inactive, QPalette.Mid, brush17)
        palette4.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        palette4.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.ButtonText, brush6)
        palette4.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Window, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette4.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette4.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush21)
#endif
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush16)
        palette4.setBrush(QPalette.Disabled, QPalette.Button, brush)
        palette4.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette4.setBrush(QPalette.Disabled, QPalette.Midlight, brush)
        palette4.setBrush(QPalette.Disabled, QPalette.Dark, brush16)
        palette4.setBrush(QPalette.Disabled, QPalette.Mid, brush17)
        palette4.setBrush(QPalette.Disabled, QPalette.Text, brush16)
        palette4.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette4.setBrush(QPalette.Disabled, QPalette.ButtonText, brush16)
        palette4.setBrush(QPalette.Disabled, QPalette.Base, brush)
        palette4.setBrush(QPalette.Disabled, QPalette.Window, brush)
        palette4.setBrush(QPalette.Disabled, QPalette.Shadow, brush6)
        palette4.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush)
        palette4.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette4.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush21)
#endif
        self.comboBox_parametros.setPalette(palette4)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(770, 450, 161, 16))
        self.pushButton_crear_netlist = QPushButton(self.centralwidget)
        self.pushButton_crear_netlist.setObjectName(u"pushButton_crear_netlist")
        self.pushButton_crear_netlist.setGeometry(QRect(20, 171, 291, 31))
        self.pushButton_crear_netlist.setStyleSheet(u"background-color:qlineargradient(spread:pad, x1:0.568, y1:0.0454545, x2:0.511, y2:0.994318, stop:0 rgba(88, 191, 162, 255), stop:1 rgba(90, 170, 126, 255));\n"
"")
        self.lineEdit_frecuencia_inicial = QLineEdit(self.centralwidget)
        self.lineEdit_frecuencia_inicial.setObjectName(u"lineEdit_frecuencia_inicial")
        self.lineEdit_frecuencia_inicial.setGeometry(QRect(530, 399, 71, 21))
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush6)
        palette5.setBrush(QPalette.Active, QPalette.Text, brush6)
        brush22 = QBrush(QColor(0, 0, 0, 128))
        brush22.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette.Active, QPalette.PlaceholderText, brush22)
#endif
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        palette5.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        brush23 = QBrush(QColor(0, 0, 0, 128))
        brush23.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush23)
#endif
        palette5.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette5.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        brush24 = QBrush(QColor(0, 0, 0, 128))
        brush24.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush24)
#endif
        self.lineEdit_frecuencia_inicial.setPalette(palette5)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(530, 379, 91, 16))
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(560, 170, 21, 16))
        self.lineEdit_z0 = QLineEdit(self.centralwidget)
        self.lineEdit_z0.setObjectName(u"lineEdit_z0")
        self.lineEdit_z0.setGeometry(QRect(590, 170, 41, 21))
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.WindowText, brush6)
        palette6.setBrush(QPalette.Active, QPalette.Text, brush6)
        brush25 = QBrush(QColor(0, 0, 0, 128))
        brush25.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Active, QPalette.PlaceholderText, brush25)
#endif
        palette6.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        palette6.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        brush26 = QBrush(QColor(0, 0, 0, 128))
        brush26.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush26)
#endif
        palette6.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette6.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        brush27 = QBrush(QColor(0, 0, 0, 128))
        brush27.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush27)
#endif
        self.lineEdit_z0.setPalette(palette6)
        self.comboBox_unidad_f1 = QComboBox(self.centralwidget)
        self.comboBox_unidad_f1.addItem("")
        self.comboBox_unidad_f1.addItem("")
        self.comboBox_unidad_f1.addItem("")
        self.comboBox_unidad_f1.addItem("")
        self.comboBox_unidad_f1.setObjectName(u"comboBox_unidad_f1")
        self.comboBox_unidad_f1.setGeometry(QRect(570, 400, 51, 22))
        self.comboBox_unidad_f1.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.comboBox_unidad_f1.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.comboBox_unidad_f1.setEditable(False)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(650, 170, 31, 20))
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(530, 430, 91, 16))
        self.lineEdit_frecuencia_final = QLineEdit(self.centralwidget)
        self.lineEdit_frecuencia_final.setObjectName(u"lineEdit_frecuencia_final")
        self.lineEdit_frecuencia_final.setGeometry(QRect(530, 450, 41, 21))
        palette7 = QPalette()
        palette7.setBrush(QPalette.Active, QPalette.WindowText, brush6)
        palette7.setBrush(QPalette.Active, QPalette.Text, brush6)
        brush28 = QBrush(QColor(0, 0, 0, 128))
        brush28.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette.Active, QPalette.PlaceholderText, brush28)
#endif
        palette7.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        palette7.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        brush29 = QBrush(QColor(0, 0, 0, 128))
        brush29.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush29)
#endif
        palette7.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette7.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        brush30 = QBrush(QColor(0, 0, 0, 128))
        brush30.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush30)
#endif
        self.lineEdit_frecuencia_final.setPalette(palette7)
        self.comboBox_unidad_f2 = QComboBox(self.centralwidget)
        self.comboBox_unidad_f2.addItem("")
        self.comboBox_unidad_f2.addItem("")
        self.comboBox_unidad_f2.addItem("")
        self.comboBox_unidad_f2.addItem("")
        self.comboBox_unidad_f2.setObjectName(u"comboBox_unidad_f2")
        self.comboBox_unidad_f2.setGeometry(QRect(570, 450, 51, 22))
        self.comboBox_unidad_f2.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.comboBox_unidad_f2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.comboBox_unidad_f2.setEditable(False)
        self.checkBox_11_touch = QCheckBox(self.centralwidget)
        self.checkBox_11_touch.setObjectName(u"checkBox_11_touch")
        self.checkBox_11_touch.setGeometry(QRect(770, 470, 70, 17))
        self.checkBox_11_touch.setChecked(True)
        self.checkBox_12_touch = QCheckBox(self.centralwidget)
        self.checkBox_12_touch.setObjectName(u"checkBox_12_touch")
        self.checkBox_12_touch.setGeometry(QRect(820, 470, 70, 17))
        self.checkBox_21_touch = QCheckBox(self.centralwidget)
        self.checkBox_21_touch.setObjectName(u"checkBox_21_touch")
        self.checkBox_21_touch.setGeometry(QRect(870, 470, 70, 17))
        self.checkBox_22_touch = QCheckBox(self.centralwidget)
        self.checkBox_22_touch.setObjectName(u"checkBox_22_touch")
        self.checkBox_22_touch.setGeometry(QRect(920, 470, 70, 17))
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(710, 190, 20, 301))
        self.line.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.comboBox_grafica_1 = QComboBox(self.centralwidget)
        self.comboBox_grafica_1.addItem("")
        self.comboBox_grafica_1.addItem("")
        self.comboBox_grafica_1.addItem("")
        self.comboBox_grafica_1.setObjectName(u"comboBox_grafica_1")
        self.comboBox_grafica_1.setGeometry(QRect(390, 510, 211, 21))
        palette8 = QPalette()
        palette8.setBrush(QPalette.Active, QPalette.WindowText, brush6)
        palette8.setBrush(QPalette.Active, QPalette.Button, brush)
        palette8.setBrush(QPalette.Active, QPalette.Light, brush)
        palette8.setBrush(QPalette.Active, QPalette.Midlight, brush)
        palette8.setBrush(QPalette.Active, QPalette.Dark, brush16)
        palette8.setBrush(QPalette.Active, QPalette.Mid, brush17)
        palette8.setBrush(QPalette.Active, QPalette.Text, brush6)
        palette8.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette8.setBrush(QPalette.Active, QPalette.ButtonText, brush6)
        palette8.setBrush(QPalette.Active, QPalette.Base, brush)
        palette8.setBrush(QPalette.Active, QPalette.Window, brush)
        palette8.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette8.setBrush(QPalette.Active, QPalette.AlternateBase, brush)
        palette8.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette8.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette8.setBrush(QPalette.Active, QPalette.PlaceholderText, brush21)
#endif
        palette8.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        palette8.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette8.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette8.setBrush(QPalette.Inactive, QPalette.Midlight, brush)
        palette8.setBrush(QPalette.Inactive, QPalette.Dark, brush16)
        palette8.setBrush(QPalette.Inactive, QPalette.Mid, brush17)
        palette8.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        palette8.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette8.setBrush(QPalette.Inactive, QPalette.ButtonText, brush6)
        palette8.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette8.setBrush(QPalette.Inactive, QPalette.Window, brush)
        palette8.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette8.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush)
        palette8.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette8.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette8.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush21)
#endif
        palette8.setBrush(QPalette.Disabled, QPalette.WindowText, brush16)
        palette8.setBrush(QPalette.Disabled, QPalette.Button, brush)
        palette8.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette8.setBrush(QPalette.Disabled, QPalette.Midlight, brush)
        palette8.setBrush(QPalette.Disabled, QPalette.Dark, brush16)
        palette8.setBrush(QPalette.Disabled, QPalette.Mid, brush17)
        palette8.setBrush(QPalette.Disabled, QPalette.Text, brush16)
        palette8.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette8.setBrush(QPalette.Disabled, QPalette.ButtonText, brush16)
        palette8.setBrush(QPalette.Disabled, QPalette.Base, brush)
        palette8.setBrush(QPalette.Disabled, QPalette.Window, brush)
        palette8.setBrush(QPalette.Disabled, QPalette.Shadow, brush6)
        palette8.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush)
        palette8.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette8.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette8.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush21)
#endif
        self.comboBox_grafica_1.setPalette(palette8)
        self.pushButton_graficar_1 = QPushButton(self.centralwidget)
        self.pushButton_graficar_1.setObjectName(u"pushButton_graficar_1")
        self.pushButton_graficar_1.setGeometry(QRect(600, 510, 75, 23))
        self.pushButton_graficar_1.setStyleSheet(u"background-color:qlineargradient(spread:pad, x1:0.443, y1:0.0454545, x2:0.568, y2:1, stop:0 rgba(91, 160, 170, 255), stop:1 rgba(199, 255, 244, 255))")
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(390, 490, 161, 16))
        self.pushButton_crear_touchstone = QPushButton(self.centralwidget)
        self.pushButton_crear_touchstone.setObjectName(u"pushButton_crear_touchstone")
        self.pushButton_crear_touchstone.setGeometry(QRect(770, 250, 291, 31))
        self.pushButton_crear_touchstone.setStyleSheet(u"background-color:qlineargradient(spread:pad, x1:0.568, y1:0.0454545, x2:0.511, y2:0.994318, stop:0 rgba(88, 191, 162, 255), stop:1 rgba(90, 170, 126, 255));")
        self.plainTextEdit_mostrar_touchstone = QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_mostrar_touchstone.setObjectName(u"plainTextEdit_mostrar_touchstone")
        self.plainTextEdit_mostrar_touchstone.setGeometry(QRect(770, 370, 291, 71))
        palette9 = QPalette()
        palette9.setBrush(QPalette.Active, QPalette.WindowText, brush6)
        brush31 = QBrush(QColor(192, 217, 210, 255))
        brush31.setStyle(Qt.SolidPattern)
        palette9.setBrush(QPalette.Active, QPalette.Button, brush31)
        palette9.setBrush(QPalette.Active, QPalette.Text, brush6)
        palette9.setBrush(QPalette.Active, QPalette.Base, brush31)
        palette9.setBrush(QPalette.Active, QPalette.Window, brush31)
        brush32 = QBrush(QColor(0, 0, 0, 128))
        brush32.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette9.setBrush(QPalette.Active, QPalette.PlaceholderText, brush32)
#endif
        palette9.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        palette9.setBrush(QPalette.Inactive, QPalette.Button, brush31)
        palette9.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        palette9.setBrush(QPalette.Inactive, QPalette.Base, brush31)
        palette9.setBrush(QPalette.Inactive, QPalette.Window, brush31)
        brush33 = QBrush(QColor(0, 0, 0, 128))
        brush33.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette9.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush33)
#endif
        palette9.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette9.setBrush(QPalette.Disabled, QPalette.Button, brush31)
        palette9.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette9.setBrush(QPalette.Disabled, QPalette.Base, brush31)
        palette9.setBrush(QPalette.Disabled, QPalette.Window, brush31)
        brush34 = QBrush(QColor(0, 0, 0, 128))
        brush34.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette9.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush34)
#endif
        self.plainTextEdit_mostrar_touchstone.setPalette(palette9)
        self.plainTextEdit_mostrar_touchstone.setStyleSheet(u"background-color:rgb(192, 217, 210)")
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(400, 250, 47, 13))
        font = QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet(u"color: rgb(110, 207, 178);")
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(400, 280, 47, 13))
        self.label_12.setFont(font)
        self.label_12.setStyleSheet(u"color: rgb(110, 207, 178);")
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(400, 310, 47, 13))
        self.label_13.setFont(font)
        self.label_13.setStyleSheet(u"color: rgb(110, 207, 178);")
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(400, 340, 47, 13))
        self.label_14.setFont(font)
        self.label_14.setStyleSheet(u"color: rgb(110, 207, 178);")
        self.label_15 = QLabel(self.centralwidget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(480, 230, 47, 13))
        self.label_16 = QLabel(self.centralwidget)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(600, 230, 61, 16))
        self.lineEdit_real_1 = QLineEdit(self.centralwidget)
        self.lineEdit_real_1.setObjectName(u"lineEdit_real_1")
        self.lineEdit_real_1.setGeometry(QRect(450, 250, 101, 21))
        palette10 = QPalette()
        palette10.setBrush(QPalette.Active, QPalette.WindowText, brush6)
        palette10.setBrush(QPalette.Active, QPalette.Text, brush6)
        brush35 = QBrush(QColor(0, 0, 0, 128))
        brush35.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette10.setBrush(QPalette.Active, QPalette.PlaceholderText, brush35)
#endif
        palette10.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        palette10.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        brush36 = QBrush(QColor(0, 0, 0, 128))
        brush36.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette10.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush36)
#endif
        palette10.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette10.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        brush37 = QBrush(QColor(0, 0, 0, 128))
        brush37.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette10.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush37)
#endif
        self.lineEdit_real_1.setPalette(palette10)
        self.lineEdit_imaginario_1 = QLineEdit(self.centralwidget)
        self.lineEdit_imaginario_1.setObjectName(u"lineEdit_imaginario_1")
        self.lineEdit_imaginario_1.setGeometry(QRect(570, 250, 101, 21))
        palette11 = QPalette()
        palette11.setBrush(QPalette.Active, QPalette.WindowText, brush6)
        palette11.setBrush(QPalette.Active, QPalette.Text, brush6)
        brush38 = QBrush(QColor(0, 0, 0, 128))
        brush38.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette11.setBrush(QPalette.Active, QPalette.PlaceholderText, brush38)
#endif
        palette11.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        palette11.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        brush39 = QBrush(QColor(0, 0, 0, 128))
        brush39.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette11.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush39)
#endif
        palette11.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette11.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        brush40 = QBrush(QColor(0, 0, 0, 128))
        brush40.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette11.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush40)
#endif
        self.lineEdit_imaginario_1.setPalette(palette11)
        self.lineEdit_real_2 = QLineEdit(self.centralwidget)
        self.lineEdit_real_2.setObjectName(u"lineEdit_real_2")
        self.lineEdit_real_2.setGeometry(QRect(450, 280, 101, 21))
        palette12 = QPalette()
        palette12.setBrush(QPalette.Active, QPalette.WindowText, brush6)
        palette12.setBrush(QPalette.Active, QPalette.Text, brush6)
        brush41 = QBrush(QColor(0, 0, 0, 128))
        brush41.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette12.setBrush(QPalette.Active, QPalette.PlaceholderText, brush41)
#endif
        palette12.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        palette12.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        brush42 = QBrush(QColor(0, 0, 0, 128))
        brush42.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette12.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush42)
#endif
        palette12.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette12.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        brush43 = QBrush(QColor(0, 0, 0, 128))
        brush43.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette12.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush43)
#endif
        self.lineEdit_real_2.setPalette(palette12)
        self.lineEdit_imaginario_2 = QLineEdit(self.centralwidget)
        self.lineEdit_imaginario_2.setObjectName(u"lineEdit_imaginario_2")
        self.lineEdit_imaginario_2.setGeometry(QRect(570, 280, 101, 21))
        palette13 = QPalette()
        palette13.setBrush(QPalette.Active, QPalette.WindowText, brush6)
        palette13.setBrush(QPalette.Active, QPalette.Text, brush6)
        brush44 = QBrush(QColor(0, 0, 0, 128))
        brush44.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette13.setBrush(QPalette.Active, QPalette.PlaceholderText, brush44)
#endif
        palette13.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        palette13.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        brush45 = QBrush(QColor(0, 0, 0, 128))
        brush45.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette13.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush45)
#endif
        palette13.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette13.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        brush46 = QBrush(QColor(0, 0, 0, 128))
        brush46.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette13.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush46)
#endif
        self.lineEdit_imaginario_2.setPalette(palette13)
        self.lineEdit_real_3 = QLineEdit(self.centralwidget)
        self.lineEdit_real_3.setObjectName(u"lineEdit_real_3")
        self.lineEdit_real_3.setGeometry(QRect(450, 310, 101, 21))
        palette14 = QPalette()
        palette14.setBrush(QPalette.Active, QPalette.WindowText, brush6)
        palette14.setBrush(QPalette.Active, QPalette.Text, brush6)
        brush47 = QBrush(QColor(0, 0, 0, 128))
        brush47.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette14.setBrush(QPalette.Active, QPalette.PlaceholderText, brush47)
#endif
        palette14.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        palette14.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        brush48 = QBrush(QColor(0, 0, 0, 128))
        brush48.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette14.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush48)
#endif
        palette14.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette14.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        brush49 = QBrush(QColor(0, 0, 0, 128))
        brush49.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette14.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush49)
#endif
        self.lineEdit_real_3.setPalette(palette14)
        self.lineEdit_imaginario_3 = QLineEdit(self.centralwidget)
        self.lineEdit_imaginario_3.setObjectName(u"lineEdit_imaginario_3")
        self.lineEdit_imaginario_3.setGeometry(QRect(570, 310, 101, 21))
        palette15 = QPalette()
        palette15.setBrush(QPalette.Active, QPalette.WindowText, brush6)
        palette15.setBrush(QPalette.Active, QPalette.Text, brush6)
        brush50 = QBrush(QColor(0, 0, 0, 128))
        brush50.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette15.setBrush(QPalette.Active, QPalette.PlaceholderText, brush50)
#endif
        palette15.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        palette15.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        brush51 = QBrush(QColor(0, 0, 0, 128))
        brush51.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette15.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush51)
#endif
        palette15.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette15.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        brush52 = QBrush(QColor(0, 0, 0, 128))
        brush52.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette15.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush52)
#endif
        self.lineEdit_imaginario_3.setPalette(palette15)
        self.lineEdit_real_4 = QLineEdit(self.centralwidget)
        self.lineEdit_real_4.setObjectName(u"lineEdit_real_4")
        self.lineEdit_real_4.setGeometry(QRect(450, 340, 101, 21))
        palette16 = QPalette()
        palette16.setBrush(QPalette.Active, QPalette.WindowText, brush6)
        palette16.setBrush(QPalette.Active, QPalette.Text, brush6)
        brush53 = QBrush(QColor(0, 0, 0, 128))
        brush53.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette16.setBrush(QPalette.Active, QPalette.PlaceholderText, brush53)
#endif
        palette16.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        palette16.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        brush54 = QBrush(QColor(0, 0, 0, 128))
        brush54.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette16.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush54)
#endif
        palette16.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette16.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        brush55 = QBrush(QColor(0, 0, 0, 128))
        brush55.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette16.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush55)
#endif
        self.lineEdit_real_4.setPalette(palette16)
        self.lineEdit_imaginario_4 = QLineEdit(self.centralwidget)
        self.lineEdit_imaginario_4.setObjectName(u"lineEdit_imaginario_4")
        self.lineEdit_imaginario_4.setGeometry(QRect(570, 340, 101, 21))
        palette17 = QPalette()
        palette17.setBrush(QPalette.Active, QPalette.WindowText, brush6)
        palette17.setBrush(QPalette.Active, QPalette.Text, brush6)
        brush56 = QBrush(QColor(0, 0, 0, 128))
        brush56.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette17.setBrush(QPalette.Active, QPalette.PlaceholderText, brush56)
#endif
        palette17.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        palette17.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        brush57 = QBrush(QColor(0, 0, 0, 128))
        brush57.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette17.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush57)
#endif
        palette17.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette17.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        brush58 = QBrush(QColor(0, 0, 0, 128))
        brush58.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette17.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush58)
#endif
        self.lineEdit_imaginario_4.setPalette(palette17)
        self.line_2 = QFrame(self.centralwidget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(340, 190, 20, 311))
        self.line_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.line_2.setFrameShape(QFrame.VLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.label_17 = QLabel(self.centralwidget)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(20, 260, 131, 16))
        self.label_18 = QLabel(self.centralwidget)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(770, 350, 131, 16))
        self.label_19 = QLabel(self.centralwidget)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(400, 220, 131, 16))
        self.label_22 = QLabel(self.centralwidget)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(140, 130, 61, 16))
        font1 = QFont()
        font1.setPointSize(12)
        self.label_22.setFont(font1)
        self.label_23 = QLabel(self.centralwidget)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(500, 130, 81, 16))
        self.label_23.setFont(font1)
        self.label_24 = QLabel(self.centralwidget)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(880, 130, 91, 16))
        self.label_24.setFont(font1)
        self.widget = QWidget(self.centralwidget)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(0, -11, 1101, 131))
        self.widget.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.label_25 = QLabel(self.widget)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(270, 50, 591, 41))
        palette18 = QPalette()
        palette18.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette18.setBrush(QPalette.Active, QPalette.Button, brush6)
        palette18.setBrush(QPalette.Active, QPalette.Light, brush6)
        palette18.setBrush(QPalette.Active, QPalette.Midlight, brush6)
        palette18.setBrush(QPalette.Active, QPalette.Dark, brush6)
        palette18.setBrush(QPalette.Active, QPalette.Mid, brush6)
        palette18.setBrush(QPalette.Active, QPalette.Text, brush)
        palette18.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette18.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette18.setBrush(QPalette.Active, QPalette.Base, brush6)
        palette18.setBrush(QPalette.Active, QPalette.Window, brush6)
        palette18.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette18.setBrush(QPalette.Active, QPalette.AlternateBase, brush6)
        palette18.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette18.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette18.setBrush(QPalette.Active, QPalette.PlaceholderText, brush9)
#endif
        palette18.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette18.setBrush(QPalette.Inactive, QPalette.Button, brush6)
        palette18.setBrush(QPalette.Inactive, QPalette.Light, brush6)
        palette18.setBrush(QPalette.Inactive, QPalette.Midlight, brush6)
        palette18.setBrush(QPalette.Inactive, QPalette.Dark, brush6)
        palette18.setBrush(QPalette.Inactive, QPalette.Mid, brush6)
        palette18.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette18.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette18.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette18.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette18.setBrush(QPalette.Inactive, QPalette.Window, brush6)
        palette18.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette18.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush6)
        palette18.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette18.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette18.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush9)
#endif
        palette18.setBrush(QPalette.Disabled, QPalette.WindowText, brush6)
        palette18.setBrush(QPalette.Disabled, QPalette.Button, brush6)
        palette18.setBrush(QPalette.Disabled, QPalette.Light, brush6)
        palette18.setBrush(QPalette.Disabled, QPalette.Midlight, brush6)
        palette18.setBrush(QPalette.Disabled, QPalette.Dark, brush6)
        palette18.setBrush(QPalette.Disabled, QPalette.Mid, brush6)
        palette18.setBrush(QPalette.Disabled, QPalette.Text, brush6)
        palette18.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette18.setBrush(QPalette.Disabled, QPalette.ButtonText, brush6)
        palette18.setBrush(QPalette.Disabled, QPalette.Base, brush6)
        palette18.setBrush(QPalette.Disabled, QPalette.Window, brush6)
        palette18.setBrush(QPalette.Disabled, QPalette.Shadow, brush6)
        palette18.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush6)
        palette18.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette18.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette18.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush9)
#endif
        self.label_25.setPalette(palette18)
        font2 = QFont()
        font2.setPointSize(22)
        self.label_25.setFont(font2)
        self.label_mex = QLabel(self.widget)
        self.label_mex.setObjectName(u"label_mex")
        self.label_mex.setGeometry(QRect(940, 20, 111, 111))
        self.label_cinv = QLabel(self.widget)
        self.label_cinv.setObjectName(u"label_cinv")
        self.label_cinv.setGeometry(QRect(20, 20, 101, 101))
        self.plainTextEdit_mostrar_netlist = QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_mostrar_netlist.setObjectName(u"plainTextEdit_mostrar_netlist")
        self.plainTextEdit_mostrar_netlist.setGeometry(QRect(20, 280, 291, 251))
        palette19 = QPalette()
        palette19.setBrush(QPalette.Active, QPalette.WindowText, brush6)
        palette19.setBrush(QPalette.Active, QPalette.Button, brush31)
        palette19.setBrush(QPalette.Active, QPalette.Text, brush6)
        palette19.setBrush(QPalette.Active, QPalette.Base, brush31)
        palette19.setBrush(QPalette.Active, QPalette.Window, brush31)
        brush59 = QBrush(QColor(0, 0, 0, 128))
        brush59.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette19.setBrush(QPalette.Active, QPalette.PlaceholderText, brush59)
#endif
        palette19.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        palette19.setBrush(QPalette.Inactive, QPalette.Button, brush31)
        palette19.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        palette19.setBrush(QPalette.Inactive, QPalette.Base, brush31)
        palette19.setBrush(QPalette.Inactive, QPalette.Window, brush31)
        brush60 = QBrush(QColor(0, 0, 0, 128))
        brush60.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette19.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush60)
#endif
        palette19.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette19.setBrush(QPalette.Disabled, QPalette.Button, brush31)
        palette19.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette19.setBrush(QPalette.Disabled, QPalette.Base, brush31)
        palette19.setBrush(QPalette.Disabled, QPalette.Window, brush31)
        brush61 = QBrush(QColor(0, 0, 0, 128))
        brush61.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette19.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush61)
#endif
        self.plainTextEdit_mostrar_netlist.setPalette(palette19)
        self.plainTextEdit_mostrar_netlist.setStyleSheet(u"background-color:rgb(192, 217, 210)")
        self.lineEdit_frecuencia_evaluar = QLineEdit(self.centralwidget)
        self.lineEdit_frecuencia_evaluar.setObjectName(u"lineEdit_frecuencia_evaluar")
        self.lineEdit_frecuencia_evaluar.setGeometry(QRect(470, 200, 61, 21))
        palette20 = QPalette()
        palette20.setBrush(QPalette.Active, QPalette.WindowText, brush6)
        palette20.setBrush(QPalette.Active, QPalette.Text, brush6)
        brush62 = QBrush(QColor(0, 0, 0, 128))
        brush62.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette20.setBrush(QPalette.Active, QPalette.PlaceholderText, brush62)
#endif
        palette20.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        palette20.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        brush63 = QBrush(QColor(0, 0, 0, 128))
        brush63.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette20.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush63)
#endif
        palette20.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette20.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        brush64 = QBrush(QColor(0, 0, 0, 128))
        brush64.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette20.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush64)
#endif
        self.lineEdit_frecuencia_evaluar.setPalette(palette20)
        self.comboBox_unidad_f3 = QComboBox(self.centralwidget)
        self.comboBox_unidad_f3.addItem("")
        self.comboBox_unidad_f3.addItem("")
        self.comboBox_unidad_f3.addItem("")
        self.comboBox_unidad_f3.addItem("")
        self.comboBox_unidad_f3.setObjectName(u"comboBox_unidad_f3")
        self.comboBox_unidad_f3.setGeometry(QRect(530, 200, 51, 22))
        self.comboBox_unidad_f3.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.comboBox_unidad_f3.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.comboBox_unidad_f3.setEditable(False)
        self.label_28 = QLabel(self.centralwidget)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(400, 190, 51, 31))
        self.pushButton_evaluar = QPushButton(self.centralwidget)
        self.pushButton_evaluar.setObjectName(u"pushButton_evaluar")
        self.pushButton_evaluar.setGeometry(QRect(620, 200, 51, 23))
        self.pushButton_evaluar.setStyleSheet(u"background-color:qlineargradient(spread:pad, x1:0.443, y1:0.0454545, x2:0.568, y2:1, stop:0 rgba(91, 160, 170, 255), stop:1 rgba(199, 255, 244, 255))")
        self.comboBox_unidad_f1_touch = QComboBox(self.centralwidget)
        self.comboBox_unidad_f1_touch.addItem("")
        self.comboBox_unidad_f1_touch.addItem("")
        self.comboBox_unidad_f1_touch.addItem("")
        self.comboBox_unidad_f1_touch.addItem("")
        self.comboBox_unidad_f1_touch.setObjectName(u"comboBox_unidad_f1_touch")
        self.comboBox_unidad_f1_touch.setGeometry(QRect(840, 180, 51, 22))
        self.comboBox_unidad_f1_touch.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.comboBox_unidad_f1_touch.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.comboBox_unidad_f1_touch.setEditable(False)
        self.label_26 = QLabel(self.centralwidget)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(940, 160, 91, 16))
        self.lineEdit_z0_touch = QLineEdit(self.centralwidget)
        self.lineEdit_z0_touch.setObjectName(u"lineEdit_z0_touch")
        self.lineEdit_z0_touch.setGeometry(QRect(960, 220, 41, 21))
        palette21 = QPalette()
        palette21.setBrush(QPalette.Active, QPalette.WindowText, brush6)
        palette21.setBrush(QPalette.Active, QPalette.Text, brush6)
        brush65 = QBrush(QColor(0, 0, 0, 128))
        brush65.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette21.setBrush(QPalette.Active, QPalette.PlaceholderText, brush65)
#endif
        palette21.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        palette21.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        brush66 = QBrush(QColor(0, 0, 0, 128))
        brush66.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette21.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush66)
#endif
        palette21.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette21.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        brush67 = QBrush(QColor(0, 0, 0, 128))
        brush67.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette21.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush67)
#endif
        self.lineEdit_z0_touch.setPalette(palette21)
        self.label_27 = QLabel(self.centralwidget)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(940, 220, 51, 16))
        self.lineEdit_frecuencia_inicial_touch = QLineEdit(self.centralwidget)
        self.lineEdit_frecuencia_inicial_touch.setObjectName(u"lineEdit_frecuencia_inicial_touch")
        self.lineEdit_frecuencia_inicial_touch.setGeometry(QRect(790, 180, 71, 21))
        palette22 = QPalette()
        palette22.setBrush(QPalette.Active, QPalette.WindowText, brush6)
        palette22.setBrush(QPalette.Active, QPalette.Text, brush6)
        brush68 = QBrush(QColor(0, 0, 0, 128))
        brush68.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette22.setBrush(QPalette.Active, QPalette.PlaceholderText, brush68)
#endif
        palette22.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        palette22.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        brush69 = QBrush(QColor(0, 0, 0, 128))
        brush69.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette22.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush69)
#endif
        palette22.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette22.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        brush70 = QBrush(QColor(0, 0, 0, 128))
        brush70.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette22.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush70)
#endif
        self.lineEdit_frecuencia_inicial_touch.setPalette(palette22)
        self.label_29 = QLabel(self.centralwidget)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(1010, 220, 51, 20))
        self.lineEdit_frecuencia_final_touch = QLineEdit(self.centralwidget)
        self.lineEdit_frecuencia_final_touch.setObjectName(u"lineEdit_frecuencia_final_touch")
        self.lineEdit_frecuencia_final_touch.setGeometry(QRect(940, 180, 41, 21))
        palette23 = QPalette()
        palette23.setBrush(QPalette.Active, QPalette.WindowText, brush6)
        palette23.setBrush(QPalette.Active, QPalette.Text, brush6)
        brush71 = QBrush(QColor(0, 0, 0, 128))
        brush71.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette23.setBrush(QPalette.Active, QPalette.PlaceholderText, brush71)
#endif
        palette23.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        palette23.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        brush72 = QBrush(QColor(0, 0, 0, 128))
        brush72.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette23.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush72)
#endif
        palette23.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette23.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        brush73 = QBrush(QColor(0, 0, 0, 128))
        brush73.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette23.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush73)
#endif
        self.lineEdit_frecuencia_final_touch.setPalette(palette23)
        self.comboBox_unidad_f2_touch = QComboBox(self.centralwidget)
        self.comboBox_unidad_f2_touch.addItem("")
        self.comboBox_unidad_f2_touch.addItem("")
        self.comboBox_unidad_f2_touch.addItem("")
        self.comboBox_unidad_f2_touch.setObjectName(u"comboBox_unidad_f2_touch")
        self.comboBox_unidad_f2_touch.setGeometry(QRect(980, 180, 51, 22))
        self.comboBox_unidad_f2_touch.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.comboBox_unidad_f2_touch.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.comboBox_unidad_f2_touch.setEditable(False)
        self.label_30 = QLabel(self.centralwidget)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(790, 160, 91, 16))
        self.checkBox_11_parameter = QCheckBox(self.centralwidget)
        self.checkBox_11_parameter.setObjectName(u"checkBox_11_parameter")
        self.checkBox_11_parameter.setGeometry(QRect(400, 410, 31, 17))
        self.checkBox_11_parameter.setChecked(True)
        self.checkBox_21_parameter = QCheckBox(self.centralwidget)
        self.checkBox_21_parameter.setObjectName(u"checkBox_21_parameter")
        self.checkBox_21_parameter.setGeometry(QRect(400, 440, 31, 17))
        self.checkBox_22_parameter = QCheckBox(self.centralwidget)
        self.checkBox_22_parameter.setObjectName(u"checkBox_22_parameter")
        self.checkBox_22_parameter.setGeometry(QRect(450, 440, 31, 17))
        self.checkBox_12_parameter = QCheckBox(self.centralwidget)
        self.checkBox_12_parameter.setObjectName(u"checkBox_12_parameter")
        self.checkBox_12_parameter.setGeometry(QRect(450, 410, 41, 17))
        self.label_31 = QLabel(self.centralwidget)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(400, 380, 111, 16))
        self.label_32 = QLabel(self.centralwidget)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(650, 400, 41, 16))
        self.lineEdit_points = QLineEdit(self.centralwidget)
        self.lineEdit_points.setObjectName(u"lineEdit_points")
        self.lineEdit_points.setGeometry(QRect(650, 430, 41, 21))
        palette24 = QPalette()
        palette24.setBrush(QPalette.Active, QPalette.WindowText, brush6)
        palette24.setBrush(QPalette.Active, QPalette.Text, brush6)
        brush74 = QBrush(QColor(0, 0, 0, 128))
        brush74.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette24.setBrush(QPalette.Active, QPalette.PlaceholderText, brush74)
#endif
        palette24.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        palette24.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        brush75 = QBrush(QColor(0, 0, 0, 128))
        brush75.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette24.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush75)
#endif
        palette24.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette24.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        brush76 = QBrush(QColor(0, 0, 0, 128))
        brush76.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette24.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush76)
#endif
        self.lineEdit_points.setPalette(palette24)
        self.lineEdit_points_touch = QLineEdit(self.centralwidget)
        self.lineEdit_points_touch.setObjectName(u"lineEdit_points_touch")
        self.lineEdit_points_touch.setGeometry(QRect(830, 220, 41, 21))
        palette25 = QPalette()
        palette25.setBrush(QPalette.Active, QPalette.WindowText, brush6)
        palette25.setBrush(QPalette.Active, QPalette.Text, brush6)
        brush77 = QBrush(QColor(0, 0, 0, 128))
        brush77.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette25.setBrush(QPalette.Active, QPalette.PlaceholderText, brush77)
#endif
        palette25.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        palette25.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        brush78 = QBrush(QColor(0, 0, 0, 128))
        brush78.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette25.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush78)
#endif
        palette25.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette25.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        brush79 = QBrush(QColor(0, 0, 0, 128))
        brush79.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette25.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush79)
#endif
        self.lineEdit_points_touch.setPalette(palette25)
        self.label_33 = QLabel(self.centralwidget)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(790, 220, 41, 16))
        MainWindow.setCentralWidget(self.centralwidget)
        self.widget.raise_()
        self.lineEdit_nombre_netlist.raise_()
        self.pushButton_abrir_netlist.raise_()
        self.pushButton_abrir_touchstone.raise_()
        self.lineEdit_nombre_touchstone.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.comboBox_grafica_2.raise_()
        self.pushButton_graficar_2.raise_()
        self.label_4.raise_()
        self.comboBox_parametros.raise_()
        self.label_5.raise_()
        self.pushButton_crear_netlist.raise_()
        self.lineEdit_frecuencia_inicial.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.lineEdit_z0.raise_()
        self.comboBox_unidad_f1.raise_()
        self.label_9.raise_()
        self.label_8.raise_()
        self.lineEdit_frecuencia_final.raise_()
        self.comboBox_unidad_f2.raise_()
        self.checkBox_11_touch.raise_()
        self.checkBox_12_touch.raise_()
        self.checkBox_21_touch.raise_()
        self.checkBox_22_touch.raise_()
        self.line.raise_()
        self.comboBox_grafica_1.raise_()
        self.pushButton_graficar_1.raise_()
        self.label_10.raise_()
        self.pushButton_crear_touchstone.raise_()
        self.plainTextEdit_mostrar_touchstone.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.lineEdit_real_1.raise_()
        self.lineEdit_imaginario_1.raise_()
        self.lineEdit_real_2.raise_()
        self.lineEdit_imaginario_2.raise_()
        self.lineEdit_real_3.raise_()
        self.lineEdit_imaginario_3.raise_()
        self.lineEdit_real_4.raise_()
        self.lineEdit_imaginario_4.raise_()
        self.line_2.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.label_24.raise_()
        self.plainTextEdit_mostrar_netlist.raise_()
        self.lineEdit_frecuencia_evaluar.raise_()
        self.comboBox_unidad_f3.raise_()
        self.label_28.raise_()
        self.pushButton_evaluar.raise_()
        self.label_26.raise_()
        self.lineEdit_z0_touch.raise_()
        self.label_27.raise_()
        self.lineEdit_frecuencia_inicial_touch.raise_()
        self.label_29.raise_()
        self.lineEdit_frecuencia_final_touch.raise_()
        self.comboBox_unidad_f2_touch.raise_()
        self.label_30.raise_()
        self.comboBox_unidad_f1_touch.raise_()
        self.checkBox_11_parameter.raise_()
        self.checkBox_21_parameter.raise_()
        self.checkBox_22_parameter.raise_()
        self.checkBox_12_parameter.raise_()
        self.label_31.raise_()
        self.label_32.raise_()
        self.lineEdit_points.raise_()
        self.lineEdit_points_touch.raise_()
        self.label_33.raise_()
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1075, 21))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Proyecto1", None))
        self.lineEdit_nombre_netlist.setText("")
        self.pushButton_abrir_netlist.setText(QCoreApplication.translate("MainWindow", u"Abrir", None))
        self.pushButton_abrir_touchstone.setText(QCoreApplication.translate("MainWindow", u"Abrir", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Cargar archivo touchstone:", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Cargar lista de nodos:", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Par\u00e1metro", None))
        self.comboBox_grafica_2.setItemText(0, QCoreApplication.translate("MainWindow", u"Carta de Smith", None))
        self.comboBox_grafica_2.setItemText(1, QCoreApplication.translate("MainWindow", u"Magnitud", None))
        self.comboBox_grafica_2.setItemText(2, QCoreApplication.translate("MainWindow", u"Fase", None))

        self.pushButton_graficar_2.setText(QCoreApplication.translate("MainWindow", u"Graficar", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Seleccionar tipo de gr\u00e1fica:", None))
        self.comboBox_parametros.setItemText(0, QCoreApplication.translate("MainWindow", u"Z", None))
        self.comboBox_parametros.setItemText(1, QCoreApplication.translate("MainWindow", u"Y", None))
        self.comboBox_parametros.setItemText(2, QCoreApplication.translate("MainWindow", u"ABCD", None))
        self.comboBox_parametros.setItemText(3, QCoreApplication.translate("MainWindow", u"S", None))
        self.comboBox_parametros.setItemText(4, QCoreApplication.translate("MainWindow", u"T", None))

        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Seleccionar par\u00e1metro:", None))
        self.pushButton_crear_netlist.setText(QCoreApplication.translate("MainWindow", u"Dibujar circuito", None))
        self.lineEdit_frecuencia_inicial.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Frecuencia inicial:", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Z0:", None))
        self.lineEdit_z0.setText(QCoreApplication.translate("MainWindow", u"50", None))
        self.comboBox_unidad_f1.setItemText(0, QCoreApplication.translate("MainWindow", u"Hz", None))
        self.comboBox_unidad_f1.setItemText(1, QCoreApplication.translate("MainWindow", u"KHz", None))
        self.comboBox_unidad_f1.setItemText(2, QCoreApplication.translate("MainWindow", u"MHz", None))
        self.comboBox_unidad_f1.setItemText(3, QCoreApplication.translate("MainWindow", u"GHz", None))

        self.comboBox_unidad_f1.setCurrentText(QCoreApplication.translate("MainWindow", u"MHz", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"ohms", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Frecuencia final:", None))
        self.lineEdit_frecuencia_final.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.comboBox_unidad_f2.setItemText(0, QCoreApplication.translate("MainWindow", u"Hz", None))
        self.comboBox_unidad_f2.setItemText(1, QCoreApplication.translate("MainWindow", u"KHz", None))
        self.comboBox_unidad_f2.setItemText(2, QCoreApplication.translate("MainWindow", u"MHz", None))
        self.comboBox_unidad_f2.setItemText(3, QCoreApplication.translate("MainWindow", u"GHz", None))

        self.comboBox_unidad_f2.setCurrentText(QCoreApplication.translate("MainWindow", u"GHz", None))
        self.checkBox_11_touch.setText(QCoreApplication.translate("MainWindow", u"11", None))
        self.checkBox_12_touch.setText(QCoreApplication.translate("MainWindow", u"12", None))
        self.checkBox_21_touch.setText(QCoreApplication.translate("MainWindow", u"21", None))
        self.checkBox_22_touch.setText(QCoreApplication.translate("MainWindow", u"22", None))
        self.comboBox_grafica_1.setItemText(0, QCoreApplication.translate("MainWindow", u"Carta de Smith", None))
        self.comboBox_grafica_1.setItemText(1, QCoreApplication.translate("MainWindow", u"Magnitud", None))
        self.comboBox_grafica_1.setItemText(2, QCoreApplication.translate("MainWindow", u"Fase", None))

        self.pushButton_graficar_1.setText(QCoreApplication.translate("MainWindow", u"Graficar", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Seleccionar tipo de gr\u00e1fica:", None))
        self.pushButton_crear_touchstone.setText(QCoreApplication.translate("MainWindow", u"Crear desde netlist", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"X11", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"X12", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"X21", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"X22", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Real", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Imaginario", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Lista:", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Datos:", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Valores:", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"Circuito", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"Par\u00e1metros", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"Touchstone", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"MODELADO Y MEDICI\u00d3N EN CUADRIPOLOS", None))
        self.label_mex.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><br/></p></body></html>", None))
        self.label_cinv.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><br/></p></body></html>", None))
        self.lineEdit_frecuencia_evaluar.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.comboBox_unidad_f3.setItemText(0, QCoreApplication.translate("MainWindow", u"Hz", None))
        self.comboBox_unidad_f3.setItemText(1, QCoreApplication.translate("MainWindow", u"KHz", None))
        self.comboBox_unidad_f3.setItemText(2, QCoreApplication.translate("MainWindow", u"MHz", None))
        self.comboBox_unidad_f3.setItemText(3, QCoreApplication.translate("MainWindow", u"GHz", None))

        self.comboBox_unidad_f3.setCurrentText(QCoreApplication.translate("MainWindow", u"GHz", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"Frecuencia", None))
        self.pushButton_evaluar.setText(QCoreApplication.translate("MainWindow", u"Evaluar", None))
        self.comboBox_unidad_f1_touch.setItemText(0, QCoreApplication.translate("MainWindow", u"Hz", None))
        self.comboBox_unidad_f1_touch.setItemText(1, QCoreApplication.translate("MainWindow", u"KHz", None))
        self.comboBox_unidad_f1_touch.setItemText(2, QCoreApplication.translate("MainWindow", u"MHz", None))
        self.comboBox_unidad_f1_touch.setItemText(3, QCoreApplication.translate("MainWindow", u"GHz", None))

        self.comboBox_unidad_f1_touch.setCurrentText(QCoreApplication.translate("MainWindow", u"MHz", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"Frecuencia final:", None))
        self.lineEdit_z0_touch.setText(QCoreApplication.translate("MainWindow", u"50", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"Z0:", None))
        self.lineEdit_frecuencia_inicial_touch.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"ohms", None))
        self.lineEdit_frecuencia_final_touch.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.comboBox_unidad_f2_touch.setItemText(0, QCoreApplication.translate("MainWindow", u"KHz", None))
        self.comboBox_unidad_f2_touch.setItemText(1, QCoreApplication.translate("MainWindow", u"MHz", None))
        self.comboBox_unidad_f2_touch.setItemText(2, QCoreApplication.translate("MainWindow", u"GHz", None))

        self.comboBox_unidad_f2_touch.setCurrentText(QCoreApplication.translate("MainWindow", u"GHz", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"Frecuencia inicial:", None))
        self.checkBox_11_parameter.setText(QCoreApplication.translate("MainWindow", u"11", None))
        self.checkBox_21_parameter.setText(QCoreApplication.translate("MainWindow", u"21", None))
        self.checkBox_22_parameter.setText(QCoreApplication.translate("MainWindow", u"22", None))
        self.checkBox_12_parameter.setText(QCoreApplication.translate("MainWindow", u"12", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"Seleccionar par\u00e1metro:", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"Puntos:", None))
        self.lineEdit_points.setText(QCoreApplication.translate("MainWindow", u"100", None))
        self.lineEdit_points_touch.setText(QCoreApplication.translate("MainWindow", u"200", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"Puntos:", None))
    # retranslateUi

